name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"   # a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake with custom background
        uses: Platane/snk/svg-only@v3
        id: snk
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Versão clara (fundo branco)
            dist/github-contribution-grid-snake.svg?color_snake=%2300ffcc&color_dots=%23333333,%2366ff99,%23ff66cc,%23ffcc00,%23ffffff&color_bg=%23ffffff
            # Versão escura (fundo cinza #0d1117 = cor padrão do GitHub dark)
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23ff66cc&color_dots=%230a0a0a,%233c7dd9,%234b91f1,%23ffcc00,%23ffffff&color_bg=%230d1117
        env:
          GITHUB_TOKE_
